### ISSUE TITLE
New docs test prevents unit tests running when it fails

### ISSUE THREAD

**Issue by calebmarchent** [facebookincubator/LogDevice#50]
Unit tests need to run regardless of the outcome of the "docs" test

**Comment by SimonKinds** [comment]
I looked into this a bit, and I see two ways of solving it. I'm not sure which one you prefer, I'd say it's mostly a matter of taste.

Either we could move the testing of the documentation (and possibly building of the documentation, since it's arguably of less priority than the unit tests), until after the unit tests have executed. It would look something like the following
```yaml
.....
      - run:
          name: Unit Tests
          working_directory: _build
          command: |
            mkdir -p ../gtest_results/unit_tests
            make ARGS="-j 8 --output-on-failure --no-compress-output -T Test" test
      - run:
          name: Collect results
          working_directory: _build
          command: |
            xsltproc ../.circleci/conv.xsl Testing/*/Test.xml > ../gtest_results/unit_tests/results.xml
          when: always
     # Documentation moved to after the unit tests
     # (could also be moved before the collection of test results)
      - run:
          name: Generate Documentation
          working_directory: _build
          command: |
            make -j 8 docs
      - run:
          name: Ensure docs not modified by build
          command: git diff -s --exit-code -- docs
....
```

or we could force the unit tests to always run by setting the `when` attribute to `always`, the same way that the `Collect results` job has it. It would look something like this.

```yaml
.....
      - run:
          name: Unit Tests
          working_directory: _build
          command: |
            mkdir -p ../gtest_results/unit_tests
            make ARGS="-j 8 --output-on-failure --no-compress-output -T Test" test
          when: always # <--------------------- this changed
      - run:
          name: Collect results
          working_directory: _build
          command: |
            xsltproc ../.circleci/conv.xsl Testing/*/Test.xml > ../gtest_results/unit_tests/results.xml
          when: always
```

In my opinion the first option makes more sense, because generating the documentation is arguably not needed at all if the unit tests fail. Let me know what you think.
